<?php
/**
 * AspectCollector.php
 * @version 8.1
 *
 * @package attributes
 * @author  weijian.ye
 * @contact 891718689@qq.com
 * @link    https://github.com/vzina
 */
declare (strict_types=1);

namespace Vzina\Attributes\Collector;

use Illuminate\Support\Arr;
use ReflectionClass;
use ReflectionProperty;

class AspectCollector extends MetadataCollector
{
    protected static array $container = [];
    protected static array $aspectRules = [];

    /**
     * Pre-compiled regex patterns for wildcard rules.
     * @var array<string, string>
     */
    protected static array $compiledPatterns = [];

    public static function setAround(string $aspect, array $classes, array $attributes, ?int $priority = null): void
    {
        if (! is_int($priority)) {
            $priority = 0;
        }

        static::override('classes.' . $aspect, fn($v) => array_merge((array) $v, $classes));
        static::override('attributes.' . $aspect, fn($v) => array_merge((array) $v, $attributes));

        static::$aspectRules[$aspect] = [
            'priority' => $priority,
            'classes' => array_merge(static::$aspectRules[$aspect]['classes'] ?? [], $classes),
            'attributes' => array_merge(static::$aspectRules[$aspect]['attributes'] ?? [], $attributes),
        ];

        // Pre-compile wildcard patterns for all new rules
        foreach (array_merge($classes, $attributes) as $rule) {
            if (str_contains($rule, '*') && ! isset(static::$compiledPatterns[$rule])) {
                static::$compiledPatterns[$rule] = '/^'
                    . str_replace('\*', '.*', preg_quote($rule, '/'))
                    . '$/';
            }
        }
    }

    public static function clear($key = null): void
    {
        if ($key) {
            Arr::forget(static::$aspectRules, $key);
            empty(static::$container['classes']) or Arr::forget(static::$container['classes'], $key);
            empty(static::$container['attributes']) or Arr::forget(static::$container['attributes'], $key);
        } else {
            static::$container = [];
            static::$aspectRules = [];
            static::$compiledPatterns = [];
        }
    }

    /**
     * Match a rule against a target string using pre-compiled regex cache.
     * Handles wildcard (*) patterns. Falls back to exact string comparison
     * when no wildcard is present.
     */
    public static function matchRule(string $rule, string $target): bool
    {
        if (isset(static::$compiledPatterns[$rule])) {
            return (bool) preg_match(static::$compiledPatterns[$rule], $target);
        }

        // Compile on-the-fly for wildcard rules not pre-cached
        if (str_contains($rule, '*')) {
            static::$compiledPatterns[$rule] = '/^'
                . str_replace('\*', '.*', preg_quote($rule, '/'))
                . '$/';
            return (bool) preg_match(static::$compiledPatterns[$rule], $target);
        }

        return $rule === $target;
    }

    public static function getRule(string $aspect): array
    {
        return static::$aspectRules[$aspect] ?? [];
    }

    public static function getPriority(string $aspect): int
    {
        return static::$aspectRules[$aspect]['priority'] ?? 0;
    }

    public static function getRules(): array
    {
        return static::$aspectRules;
    }

    public static function serialize(): string
    {
        return serialize([static::$aspectRules, static::$container]);
    }

    public static function deserialize(string $metadata): bool
    {
        [$rules, $container] = (array) unserialize($metadata, ['allowed_classes' => []]);
        static::$aspectRules = (array) $rules;
        static::$container = (array) $container;
        return true;
    }

    /**
     * Export rules and container to a PHP cache file for OPcache acceleration.
     */
    public static function exportToFile(string $filePath): void
    {
        $export = var_export([static::$aspectRules, static::$container, static::$compiledPatterns], true);
        $code = "<?php\n// Auto-generated by vzina/attributes, do not edit.\n"
              . "// Generated at: " . date('Y-m-d H:i:s') . "\n"
              . "return {$export};\n";
        file_put_contents($filePath, $code, LOCK_EX);

        if (function_exists('opcache_invalidate')) {
            @opcache_invalidate($filePath, true);
        }
        if (function_exists('opcache_compile_file')) {
            @opcache_compile_file($filePath);
        }
    }

    /**
     * Load rules, container, and compiled patterns from a PHP cache file.
     * @return array{0: array, 1: array, 2: array} [rules, container, compiledPatterns]
     */
    public static function loadFromFile(string $filePath): array
    {
        if (! file_exists($filePath)) {
            return [[], [], []];
        }
        $data = (array) include $filePath;
        // include 可能返回 int(1) 如果文件没有 return 语句
        if (! isset($data[0]) || ! is_array($data[0])) {
            $data = [[], [], []];
        }
        [$rules, $container, $patterns] = $data + [[], [], []];
        static::$aspectRules = (array) $rules;
        static::$container = (array) $container;
        static::$compiledPatterns = (array) $patterns;
        return [static::$aspectRules, static::$container, static::$compiledPatterns];
    }

    public static function load(string $className): array
    {
        $refClass = new ReflectionClass($className);
        $properties = $refClass->getProperties(ReflectionProperty::IS_PUBLIC);

        $keys = ['classes', 'attributes', 'priority'];
        $ret = [];
        foreach ($properties as $property) {
            $name = $property->getName();
            if (in_array($name, $keys)) {
                $ret[$name] = $property->getDefaultValue();
            }
        }

        return $ret;
    }

    public static function getContainer(): array
    {
        return self::$container;
    }
}