<?php
/**
 * MetadataCollector.php
 * @version 8.1
 *
 * @package attributes
 * @author  weijian.ye
 * @contact 891718689@qq.com
 * @link    https://github.com/vzina
 */
declare (strict_types=1);

namespace Vzina\Attributes\Collector;

use Closure;
use Illuminate\Support\Arr;

abstract class MetadataCollector implements MetadataCollectorInterface
{
    protected static array $container = [];

    public static function get(string $key, $default = null)
    {
        return Arr::get(static::$container, $key) ?? $default;
    }

    public static function set(string $key, $value): void
    {
        Arr::set(static::$container, $key, $value);
    }

    public static function has(string $key): bool
    {
        return Arr::has(static::$container, $key);
    }

    public static function clear($key = null): void
    {
        if ($key) {
            Arr::forget(static::$container, $key);
        } else {
            static::$container = [];
        }
    }

    public static function serialize(): string
    {
        return serialize(static::$container);
    }

    public static function deserialize(string $metadata): bool
    {
        static::$container = unserialize($metadata, ['allowed_classes' => []]);
        return true;
    }

    /**
     * Export container to a PHP cache file for OPcache acceleration.
     */
    public static function exportToFile(string $filePath): void
    {
        $export = var_export(static::$container, true);
        $code = "<?php\n// Auto-generated by vzina/attributes, do not edit.\n"
              . "// Generated at: " . date('Y-m-d H:i:s') . "\n"
              . "return {$export};\n";
        file_put_contents($filePath, $code, LOCK_EX);

        if (function_exists('opcache_invalidate')) {
            @opcache_invalidate($filePath, true);
        }
        if (function_exists('opcache_compile_file')) {
            @opcache_compile_file($filePath);
        }
    }

    /**
     * Load container from a PHP cache file.
     * @return array The loaded data (also stored in static::$container).
     */
    public static function loadFromFile(string $filePath): array
    {
        if (! file_exists($filePath)) {
            return [];
        }
        return static::$container = (array) include $filePath;
    }

    public static function list(): array
    {
        return static::$container;
    }

    public static function override(string $key, Closure $closure): void
    {
        $value = null;
        if (self::has($key)) {
            $value = self::get($key);
        }
        $value = $closure($value);

        static::set($key, $value);
    }
}